### ISSUE TITLE
mutation: insert one-to-one を行う

### ISSUE THREAD

**Issue by r-sugi** [r-sugi/nextjs-tdd-template#18]
下記のmutationがエラーになる

```
mutation MyMutation{
  insert_memberStatusActivities_one(
    object: {
      status: "resigned",
      memberId: "ff4b01ee-15e9-4e2e-acb3-25a0347af7c1",
      memberResigned: {
        data: {
          memberId: "ff4b01ee-15e9-4e2e-acb3-25a0347af7c1",
          reasonType: "ttt",
          agreement: true,
          email: "aaa",
          reasonDetail: "dddd",
        }
    	}
    }
  ) {
    memberId
    status
    memberResigned {
      reasonType
      reasonDetail
      agreement
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Not-NULL violation. null value in column \"statusActivityId\" of relation \"memberResigned\" violates not-null constraint",
      "extensions": {
        "path": "$.selectionSet.insert_memberStatusActivities_one.args.object[0].memberResigned.data",
        "code": "constraint-violation"
     

```

**Comment by r-sugi** [comment]
author has_one post の場合、hasuraは子レコードから先に生成する。
そのため親レコードid(外部参照キー)が存在しないため、子レコードを保存できずにエラーになる

例
```
mutation MyMutation {
  insert_authors_one(object: {post: {data: {title: "tttt"}}}) {
    post {
      author_id
      title
    }
    id
  }
}
```

手動でテーブルメタデータを変更し(``insertion_order: after_parent`)、テーブルに適用する(`hasura metadata apply`)
```
table:
  name: authors
  schema: public
object_relationships:
  - name: post
    using:
      manual_configuration:
        column_mapping:
          id: author_id
        insertion_order: after_parent <== 指定する
        remote_table:
          name: posts
          schema: public
```
