### ISSUE TITLE
DB timestamptz column always saved as UTC date

### ISSUE THREAD

**Issue by r-sugi** [r-sugi/nextjs-tdd-template#29]
### summary
(timestamp with time zone) column always saved as UTC date

colum type: timestamptz
asis: 2024-04-19T19:05:35.434948+00:00
tobe: 2024-04-20T04:05:35.434948+09:00 (Asia/Tokyo) 

![スクリーンショット 2024-04-20 4 09 03](https://github.com/r-sugi/nextjs-tdd-template/assets/20441979/9eeae7d9-9729-4087-93d4-3b7a145e5b2f)

![スクリーンショット 2024-04-20 4 06 50](https://github.com/r-sugi/nextjs-tdd-template/assets/20441979/0188dd60-ba10-4dbf-9009-2a0c5838c94e)

### example
timestamp value converted to Date by browser Time Zone (relatively)

```
DB value: '2024-04-15T11:32:45.104337+00:00'
browser script: new Date(res.createdAt) => Mon Apr 15 2024 20:32:45 GMT+0900 (日本標準時)
```

![スクリーンショット 2024-04-20 5 00 48](https://github.com/r-sugi/nextjs-tdd-template/assets/20441979/1c49b59a-2074-4c9e-9bce-0e3f63dedcc2)

**Comment by r-sugi** [comment]
```
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      TZ: "Asia/Tokyo"
```
